apiVersion: v1
kind: Secret
metadata:
  name: jfragcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJzaXZhMTIwNC5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWkc5amEyVnlZM0psWkRwRWIyTnJaWEpqY21Wa1FERXlNdz09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
